---
- name: Copy config to local VM
  become: yes
  copy:
    src: /vagrant/admin.conf
    dest: /etc/kubernetes/admin.conf
    owner: root
    group: root
    mode: 0600

- name: Ensure local config
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Copy config to home directory
  become: yes
  copy:
    src: /vagrant/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: 0600

#- name: Update Environment
#  become: yes
#  lineinfile:
#    path: /home/ubuntu/.bashrc
#    regexp: '^export KUBECONFIG='
#    line: 'export KUBECONFIG=/home/ubuntu/admin.conf'
#    state: present

- name: Join Kubernetes Cluster
  become: yes
  command: "kubeadm join --token 2f1a31.00f66dec74fd53f3 172.42.42.101:6443 --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification"
