FROM python:2-alpine

ADD https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl /usr/local/bin/kubectl
RUN chmod +x /usr/local/bin/kubectl
COPY detective.py /detective.py
RUN chmod 755 /detective.py
ENTRYPOINT /detective.py

